import type { AuditReport, CheckStatus } from '../core/types';
import { GROUP_LABELS, groupResults, scoreVerdict } from './common';

const STATUS_MARKS: Record<CheckStatus, string> = {
  pass: 'PASS',
  fail: '**FAIL**',
  warn: 'WARN',
  skip: 'SKIP',
};

export function renderMarkdown(report: AuditReport): string {
  const lines: string[] = [];
  const host = new URL(report.url).hostname;

  lines.push(`# Livecheck Report — ${host}`);
  lines.push('');
  lines.push(`- **URL:** ${report.url}`);
  lines.push(`- **Checked at:** ${report.startedAt}`);
  lines.push(`- **Score:** ${report.score}/100 — ${scoreVerdict(report.score)}`);
  lines.push(
    `- **Summary:** ${report.summary.pass} passed, ${report.summary.fail} failed, ${report.summary.warn} warnings, ${report.summary.skip} skipped`
  );
  lines.push('');

  for (const [group, results] of groupResults(report)) {
    lines.push(`## ${GROUP_LABELS[group]}`);
    lines.push('');
    lines.push('| Status | Check | Detail |');
    lines.push('| ------ | ----- | ------ |');
    for (const result of results) {
      const detail = (result.detail ?? '').replace(/\|/g, '\\|');
      lines.push(`| ${STATUS_MARKS[result.status]} | ${result.title} | ${detail} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    '_This report is a point-in-time snapshot generated by [Livecheck](https://github.com/Ibrahim106/livecheck). It reflects observable behavior during the audit only and is provided as-is, without warranty of any kind._'
  );
  lines.push('');
  return lines.join('\n');
}
