import type { Project, WhiteLabelSettings } from './types';
import { FIXES, PACKAGE_PRICE } from './mockData';
import { formatDate } from './utils';

export function buildCertificateHtml(project: Project, wl: WhiteLabelSettings): string {
  const issuedTo = wl.enabledByDefault || project.whiteLabel ? wl.agencyName : 'Livecheck';
  const price = project.whiteLabel ? project.markupPrice ?? wl.resalePrice : PACKAGE_PRICE;
  const accent = wl.accentColor || '#10b981';
  const fixRows = FIXES.map(
    (f) => `<tr>
      <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;font-weight:600;color:#111827;">${f.label}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #e5e7eb;color:#059669;font-weight:600;text-align:right;">&#10003; Verified</td>
    </tr>`
  ).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Service Completion Certificate — ${project.siteUrl}</title>
</head>
<body style="margin:0;background:#f4f4f5;font-family:Helvetica,Arial,sans-serif;padding:40px 16px;">
  <div style="max-width:680px;margin:0 auto;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e5e7eb;box-shadow:0 10px 30px rgba(0,0,0,0.08);">
    <div style="background:${accent};padding:28px 36px;color:#04140f;">
      <div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;opacity:0.75;font-weight:700;">Service Completion Certificate</div>
      <div style="font-size:26px;font-weight:800;margin-top:6px;">${issuedTo}</div>
    </div>
    <div style="padding:32px 36px;">
      <p style="color:#374151;font-size:14px;line-height:1.6;margin:0 0 20px;">
        This certifies that the website below has been audited and remediated under the Livecheck
        Last-Mile Rescue Package. All five scoped technical fixes have been verified complete and
        signed off by a human QA reviewer.
      </p>
      <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px;">
        <tr><td style="padding:6px 0;color:#6b7280;width:160px;">Client</td><td style="padding:6px 0;font-weight:600;color:#111827;">${project.clientName}</td></tr>
        <tr><td style="padding:6px 0;color:#6b7280;">Website</td><td style="padding:6px 0;font-weight:600;color:#111827;">${project.siteUrl}</td></tr>
        <tr><td style="padding:6px 0;color:#6b7280;">Project Reference</td><td style="padding:6px 0;font-weight:600;color:#111827;">${project.id.toUpperCase()}</td></tr>
        <tr><td style="padding:6px 0;color:#6b7280;">Completion Date</td><td style="padding:6px 0;font-weight:600;color:#111827;">${formatDate(project.updatedAt)}</td></tr>
        <tr><td style="padding:6px 0;color:#6b7280;">Package Value</td><td style="padding:6px 0;font-weight:600;color:#111827;">$${price}</td></tr>
      </table>
      <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
        <thead>
          <tr><th style="text-align:left;padding:8px 14px;background:#f9fafb;font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#6b7280;">Scope of Work</th><th style="text-align:right;padding:8px 14px;background:#f9fafb;font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#6b7280;">Status</th></tr>
        </thead>
        <tbody>${fixRows}</tbody>
      </table>
      <p style="color:#374151;font-size:13px;line-height:1.6;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:14px 16px;">
        <strong>30-Day Assurance:</strong> Any regression across the five items listed above within 30 days
        of the completion date will be corrected at no additional cost. Custom backend development or
        third-party API integration work is explicitly out of scope for this certificate and is billed
        separately at an hourly rate upon written approval.
      </p>
      <div style="margin-top:32px;display:flex;justify-content:space-between;align-items:flex-end;">
        <div>
          <div style="font-family:Georgia, serif;font-size:22px;color:#111827;border-bottom:2px solid #111827;display:inline-block;padding-bottom:2px;">${issuedTo}</div>
          <div style="font-size:11px;color:#9ca3af;margin-top:4px;">Authorized Delivery Partner</div>
        </div>
        <div style="font-size:11px;color:#9ca3af;text-align:right;">Certificate ID<br/><span style="color:#111827;font-weight:600;">${project.id.toUpperCase()}-CERT</span></div>
      </div>
    </div>
    <div style="background:#fafafa;border-top:1px solid #e5e7eb;padding:14px 36px;font-size:11px;color:#9ca3af;">
      Generated by Livecheck — the last-mile deployment rescue layer for AI-built websites.
    </div>
  </div>
</body>
</html>`;
}

export function downloadCertificate(project: Project, wl: WhiteLabelSettings) {
  const html = buildCertificateHtml(project, wl);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.siteUrl.replace(/[^a-z0-9.-]/gi, '_')}-completion-certificate.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
